"""Downstream SDK export tier for mt5cli."""

from __future__ import annotations

STABLE_SDK_EXPORTS: frozenset[str] = frozenset({
    "AccountSpec",
    "MT5Client",
    "Mt5CliError",
    "Mt5ConnectionError",
    "Mt5OperationError",
    "Mt5SchemaError",
    "OrderFillingMode",
    "OrderSide",
    "OrderTimeMode",
    "PositionSide",
    "ProjectionMode",
    "ExecutionStatus",
    "MarginVolume",
    "OrderExecutionResult",
    "OrderLimits",
    "RateTarget",
    "ThrottledHistoryUpdater",
    "build_config",
    "build_rate_targets",
    "calculate_account_projected_margin_ratio",
    "calculate_margin_and_volume",
    "calculate_new_position_margin_ratio",
    "calculate_projected_margin_ratio",
    "calculate_positions_margin",
    "calculate_positions_margin_by_symbol",
    "calculate_positions_margin_safe",
    "calculate_spread_ratio",
    "calculate_symbol_group_margin_ratio",
    "calculate_trailing_stop_updates",
    "calculate_volume_by_margin",
    "close_open_positions",
    "collect_history",
    "collect_latest_closed_rates_by_granularity",
    "collect_latest_closed_rates_for_accounts",
    "collect_latest_rates_for_accounts_with_retries",
    "create_trading_client",
    "detect_position_side",
    "determine_order_limits",
    "drop_forming_rate_bar",
    "ensure_symbol_selected",
    "estimate_order_margin",
    "extract_tick_price",
    "fetch_latest_closed_rates",
    "fetch_latest_closed_rates_for_trading_client",
    "fetch_latest_closed_rates_indexed",
    "get_account_snapshot",
    "get_positions_frame",
    "get_symbol_snapshot",
    "get_tick_snapshot",
    "load_rate_series_by_granularity",
    "load_rate_series_from_sqlite",
    "mt5_session",
    "mt5_trading_session",
    "normalize_order_volume",
    "place_market_order",
    "resolve_account_spec",
    "resolve_account_specs",
    "update_history",
    "update_history_with_config",
    "update_sltp_for_open_positions",
    "update_trailing_stop_loss_for_open_positions",
})

__all__ = ["STABLE_SDK_EXPORTS"]
